"""add_methodology_to_verification_logs

Revision ID: 161227689933
Revises: 590f006db792
Create Date: 2026-09-14 10:46:48.028618

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '161227689933'
down_revision: str | Sequence[str] | None = '590f006db792'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_logs', sa.Column('methodology', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_logs', 'methodology')
    # ### end Alembic commands ###
