"""Update embedding to 768 dims

Revision ID: 191d43501fef
Revises: f50d5bcdf579
Create Date: 2026-09-11 12:00:55.420369

"""
from collections.abc import Sequence

import pgvector
import pgvector.sqlalchemy

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '191d43501fef'
down_revision: str | Sequence[str] | None = 'f50d5bcdf579'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True)
    # ### end Alembic commands ###
