"""phase5_signature_fingerprints_table

Revision ID: 34b64a84a745
Revises: 7e60a1a54a68
Create Date: 2026-09-23 12:20:33.458267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b64a84a745'
down_revision: Union[str, Sequence[str], None] = '7e60a1a54a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature_fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False, comment="E.g. 'RBM Official Letterhead', 'Ministry of Finance Stamp', 'Confirmed WhatsApp Forgery'"),
    sa.Column('phash_hex', sa.String(length=32), nullable=False, comment='64-bit pHash as hex string. Compare via Hamming distance.'),
    sa.Column('reference_source_url', sa.String(length=500), nullable=True),
    sa.Column('is_known_forgery', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('added_by', sa.String(length=100), nullable=True, comment='Admin or pipeline that added this entry'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signature_fingerprints_date_added'), 'signature_fingerprints', ['date_added'], unique=False)
    op.create_index(op.f('ix_signature_fingerprints_id'), 'signature_fingerprints', ['id'], unique=False)
    op.create_index(op.f('ix_signature_fingerprints_institution_id'), 'signature_fingerprints', ['institution_id'], unique=False)
    op.create_index(op.f('ix_signature_fingerprints_phash_hex'), 'signature_fingerprints', ['phash_hex'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signature_fingerprints_phash_hex'), table_name='signature_fingerprints')
    op.drop_index(op.f('ix_signature_fingerprints_institution_id'), table_name='signature_fingerprints')
    op.drop_index(op.f('ix_signature_fingerprints_id'), table_name='signature_fingerprints')
    op.drop_index(op.f('ix_signature_fingerprints_date_added'), table_name='signature_fingerprints')
    op.drop_table('signature_fingerprints')
    # ### end Alembic commands ###
