"""Add Phase 2 institutional alerts, user submissions, and verification logs

Revision ID: 3bf2588aef25
Revises: 191d43501fef
Create Date: 2026-09-11 12:20:25.594492

"""
from collections.abc import Sequence

import pgvector
import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3bf2588aef25'
down_revision: str | Sequence[str] | None = '191d43501fef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('verified_social', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=False)
    op.create_index(op.f('ix_institutions_sector'), 'institutions', ['sector'], unique=False)
    op.create_table('submission_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('representative_text', sa.Text(), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_clusters_id'), 'submission_clusters', ['id'], unique=False)
    op.create_table('verification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence_sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_logs_created_at'), 'verification_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_verification_logs_id'), 'verification_logs', ['id'], unique=False)
    op.create_index(op.f('ix_verification_logs_verdict'), 'verification_logs', ['verdict'], unique=False)
    op.create_table('institutional_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('alert_text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutional_alerts_id'), 'institutional_alerts', ['id'], unique=False)
    op.create_table('user_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_text', sa.Text(), nullable=False),
    sa.Column('extracted_entities', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['submission_clusters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_submissions_id'), 'user_submissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_submissions_id'), table_name='user_submissions')
    op.drop_table('user_submissions')
    op.drop_index(op.f('ix_institutional_alerts_id'), table_name='institutional_alerts')
    op.drop_table('institutional_alerts')
    op.drop_index(op.f('ix_verification_logs_verdict'), table_name='verification_logs')
    op.drop_index(op.f('ix_verification_logs_id'), table_name='verification_logs')
    op.drop_index(op.f('ix_verification_logs_created_at'), table_name='verification_logs')
    op.drop_table('verification_logs')
    op.drop_index(op.f('ix_submission_clusters_id'), table_name='submission_clusters')
    op.drop_table('submission_clusters')
    op.drop_index(op.f('ix_institutions_sector'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
