"""add_fraud_intelligence_tables

Revision ID: 590f006db792
Revises: add_dual_verdict_system
Create Date: 2026-09-14 10:06:45.546646

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '590f006db792'
down_revision: str | Sequence[str] | None = 'add_dual_verdict_system'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submission_clusters', 'submission_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('submission_clusters', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('submission_clusters', 'first_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('submission_clusters', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('submission_clusters', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('submission_clusters', 'first_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('submission_clusters', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('submission_clusters', 'submission_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
