"""Add embedding to SubmissionCluster

Revision ID: 5a56bc5f4dd4
Revises: 3bf2588aef25
Create Date: 2026-09-11 15:26:50.668044

"""
from collections.abc import Sequence

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5a56bc5f4dd4'
down_revision: str | Sequence[str] | None = '3bf2588aef25'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_clusters', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_clusters', 'embedding')
    # ### end Alembic commands ###
