"""phase1_canonical_verdict_actionable_advice_sub_scores

Revision ID: 7e60a1a54a68
Revises: 161227689933
Create Date: 2026-09-23 11:53:33.046031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e60a1a54a68'
down_revision: Union[str, Sequence[str], None] = '161227689933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_logs', sa.Column('canonical_verdict', sa.String(length=50), nullable=True, comment='One of: VERIFIED_TRUE, VERIFIED_FALSE, HIGH_RISK_SCAM, PENDING_VERIFICATION, UNVERIFIED'))
    op.add_column('verification_logs', sa.Column('sub_scores', sa.JSON(), nullable=True))
    op.add_column('verification_logs', sa.Column('official_sources', sa.JSON(), nullable=True))
    op.add_column('verification_logs', sa.Column('actionable_advice', sa.Text(), nullable=True))
    op.create_index(op.f('ix_verification_logs_canonical_verdict'), 'verification_logs', ['canonical_verdict'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_logs_canonical_verdict'), table_name='verification_logs')
    op.drop_column('verification_logs', 'actionable_advice')
    op.drop_column('verification_logs', 'official_sources')
    op.drop_column('verification_logs', 'sub_scores')
    op.drop_column('verification_logs', 'canonical_verdict')
    # ### end Alembic commands ###
