"""phase6_source_trust_tier

Revision ID: 91d572397d9b
Revises: 34b64a84a745
Create Date: 2026-09-23 12:27:24.654795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d572397d9b'
down_revision: Union[str, Sequence[str], None] = '34b64a84a745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('trust_tier', sa.Integer(), nullable=False, server_default="2"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'trust_tier')
    # ### end Alembic commands ###
